spring.application.name=ANDROID_PROJECT

# Railway définit le port automatiquement via la variable PORT
server.port=${PORT:8080}

# Connexion DB : Utilise les variables définies dans l'interface Railway
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=true

# Hikari
spring.datasource.hikari.maximum-pool-size=5