spring.application.name=ANDROID_PROJECT

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ? Désactiver la validation Hikari au démarrage
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=-1
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

# ? Ne pas valider la connexion au démarrage
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.datasource.hikari.validate-connection=false

spring.web.cors.allowed-origins=*